/**
 * Facebook Firefox Toolbar Software License 
 * Copyright (c) 2006 Facebook, Inc. 
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (which, together with any graphical images included with such
 * software, are collectively referred to below as the "Software") to (a) use,
 * reproduce, display, distribute, execute, and transmit the Software, (b)
 * prepare derivative works of the Software (excluding any graphical images
 * included with the Software, which may not be modified or altered), and (c)
 * permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.  
 *
 * Facebook, Inc. retains ownership of the Software and all associated
 * intellectual property rights.  All rights not expressly granted in this
 * license are reserved by Facebook, Inc.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

function debug(s) { dump('** login.js: [' + s + ']\n'); }

var Cc = Components.classes;
var Ci = Components.interfaces;

// load FacebookLoginClient code
Cc['@mozilla.org/moz/jssubscript-loader;1']
    .getService(Ci.mozIJSSubScriptLoader)
    .loadSubScript('chrome://facebook/content/facebook.js');

var client = new FacebookLoginClient();

function startup() {
    if (client.fbSvc.loggedIn) {
        debug('already logged in!');
        window.close();
    } else if (!client.authToken) {
        debug('requesting token');
        try {
        client.callMethod('facebook.auth.createToken', [], function(req) {
            debug('received token response:');
            debug( req.responseText); 
            client.authToken = req.xmldata;
            debug('token is: '+client.authToken);
            startup();
        });
        } catch (e) {
            debug('exception: ' + e);
        }
    } else {
        var browser = document.getElementById('facebook-login-body');
        browser.setAttribute('src', 'http://www.facebook.com/login.php?popup&v=1.0&api_key=' +
                             client.fbSvc.apiKey + '&auth_token=' + client.authToken);
        browser.style.display = '';
        document.getElementById('throbber-box').style.display = 'none';
        debug('loading login page');
    }
}
window.addEventListener('load', startup, false);

function done() {
    debug('done()');
    if (!client.authToken) {
        window.close();
        return false;
    }
    debug(client.authToken);
    client.callMethod('facebook.auth.getSession', ['auth_token='+client.authToken], function(req) {
        debug('received session response:');
        debug(req.xmldata);
        var data = req.xmldata;
        var sessionKey    = data.session_key;
        var sessionSecret = data.secret;
        var uid           = data.uid;
        if (sessionKey && sessionSecret && uid) {
            client.fbSvc.sessionStart(sessionKey, sessionSecret, uid);
            client.authToken  = null;
            debug('session: ' + sessionKey + ', uid: ' + uid + ', secret: ' + sessionSecret);
        }
        window.setTimeout('window.close()', 1);
    });
    // in case the request fails, let's just force a 4 second timeout
    window.setTimeout('window.close()', 4000);
    return false;
}

dump('loaded login.js');
