/**
 * Facebook Firefox Toolbar Software License 
 * Copyright (c) 2006 Facebook, Inc. 
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (which, together with any graphical images included with such
 * software, are collectively referred to below as the "Software") to (a) use,
 * reproduce, display, distribute, execute, and transmit the Software, (b)
 * prepare derivative works of the Software (excluding any graphical images
 * included with the Software, which may not be modified or altered), and (c)
 * permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.  
 *
 * Facebook, Inc. retains ownership of the Software and all associated
 * intellectual property rights.  All rights not expressly granted in this
 * license are reserved by Facebook, Inc.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

function NotifierLoad() {
    debug('NotifierLoad', window.arguments[1]);
    document.getElementById('pic').setAttribute('src', window.arguments[0]);
    document.getElementById('label').appendChild(document.createTextNode(window.arguments[1]));
    window.setTimeout('window.close();', 10000);
    window.addEventListener('mouseup', NotifierClick, false);
}
function NotifierClick() {
    debug('click', window.arguments[1]);
    window.close();
    if (window.arguments[2]) {
        window.open(window.arguments[2]);
    }
}
function NotifierUnload() {
    debug('unload', window.arguments[1]);
    window.arguments[3].value--;
}
// For some reason window.onload doesn't seem to get triggered if we are
// opening mulitple windows at a time.  Need to use DOMContentLoaded instead.
document.addEventListener("DOMContentLoaded", NotifierLoad, false); 
window.addEventListener('unload', NotifierUnload, false);
debug('loaded notifier.js', window.arguments.length);
