/**
 * Facebook Firefox Toolbar Software License 
 * Copyright (c) 2007 Facebook, Inc. 
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (which, together with any graphical images included with such
 * software, are collectively referred to below as the "Software") to (a) use,
 * reproduce, display, distribute, execute, and transmit the Software, (b)
 * prepare derivative works of the Software (excluding any graphical images
 * included with the Software, which may not be modified or altered), and (c)
 * permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.  
 *
 * Facebook, Inc. retains ownership of the Software and all associated
 * intellectual property rights.  All rights not expressly granted in this
 * license are reserved by Facebook, Inc.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

var Cc = Components.classes;
var Ci = Components.interfaces;

var prefSvc = Cc['@mozilla.org/preferences-service;1'].getService(Ci.nsIPrefBranch);

// this works for loading or saving, strangely enough...
function TouchSettings(save) {
  var checkboxes = document.getElementsByTagName('checkbox');
  for (var i = 0; i < checkboxes.length; i++) {
    var node = checkboxes[i];
    var pref = 'extensions.' + node.id.replace(/-/g, '.');
    if (save) {
      prefSvc.setBoolPref(pref, node.checked);
    } else {
      node.checked = prefSvc.getBoolPref(pref);
    }
  }
  var textboxes = document.getElementsByTagName('textbox');
  for (var i = 0; i < textboxes.length; i++) {
    var node = textboxes[i];
    var pref = 'extensions.' + node.id.replace(/-/g, '.');
    if (save) {
      prefSvc.setCharPref(pref, node.value);
    } else {
      node.value = prefSvc.getCharPref(pref);
    }
  }
  if (!save && navigator.platform.indexOf('Mac') == -1) {
    document.getElementById('facebook-growlbox').style.display = 'none';
  }
}
