/**
 * Facebook Firefox Toolbar Software License
 * Copyright (c) 2009 Facebook, Inc.
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (which, together with any graphical images included with such
 * software, are collectively referred to below as the "Software") to (a) use,
 * reproduce, display, distribute, execute, and transmit the Software, (b)
 * prepare derivative works of the Software (excluding any graphical images
 * included with the Software, which may not be modified or altered), and (c)
 * permit third-parties to whom the Software is furnished to do so, all
 * subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * Facebook, Inc. retains ownership of the Software and all associated
 * intellectual property rights.  All rights not expressly granted in this
 * license are reserved by Facebook, Inc.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

// Debugging.
function LOG(s) {
  if (!opener.LOG)
    return;
  opener.LOG(s);
}

var TaggingDialog = {
  _params: null,
  _friendList: null,
  _tagText: null,

  onLoad: function() {
    this._friendList = document.getElementById("friendList");
    this._tagText = document.getElementById("tagText");

    this._params = window.arguments[0];
    if (!this._params) {
      LOG("Error: no arguments passed to this dialog");
      return;
    }
    this._params.tag = null;
    for each (var friend in this._params.friends) {
      var item = document.createElement("listitem");
      item.setAttribute("label", friend.name);
      item.setAttribute("type", "checkbox");
      item.friend = friend;
      this._friendList.appendChild(item);
    }
  },

  _getCheckedFriend: function() {
    for (var i = 0; i < this._friendList.itemCount; i++) {
      var item = this._friendList.getItemAtIndex(i);
      if (item.checked)
        return item.friend;
    }
    return null;
  },

  _createPeopleTag: function(friend) {
    var tag = new this._params.PeopleTag(friend,
                                         this._params.offsetXPercent,
                                         this._params.offsetYPercent);
    this._params.tag = tag;
  },

  _createTextTag: function(label) {
    var tag = new this._params.TextTag(label,
                                       this._params.offsetXPercent,
                                       this._params.offsetYPercent);
    this._params.tag = tag;
  },

  onAccept: function() {
    var checkedFriend = this._getCheckedFriend();
    if (checkedFriend) {
      this._createPeopleTag(checkedFriend);
      return;
    }
    if (this._tagText.value.length == 0) {
      return;
    }
    this._createTextTag(this._tagText.value);
  },

  _filterFriends: function(text) {
    function matches(itemText, filterText) {
      // If there is no text, show all items.
      if (filterText == "")
        return true;
      // Case insensitive matching.
      return itemText.search(new RegExp(filterText, "i")) != -1;
    };

    var visibleItemCount = 0;
    var lastVisibleItem;
    for (var i = 0; i < this._friendList.itemCount; i++) {
      var item = this._friendList.getItemAtIndex(i);
      item.setAttribute("checked", "false");
      item.hidden = !matches(item.friend.name, text);
      if (!item.hidden) {
        visibleItemCount++;
        lastVisibleItem = item;
      }
    }
    // If there is only one matched item, select it. When the dialog will be
    // accepted, this item will be used for the tag.
    if (visibleItemCount == 1) {
      lastVisibleItem.checked = true;
      lastVisibleItem.setAttribute("checked", "true");
    }
    // HACK: When list items hidden attribute changes from true to false, they
    // aren't shown back. This hack hides the listbox and shows it again so that
    // these items appear again. The unfortunate side effect is that the
    // listbox flickers.
    this._friendList.hidden = true;
    var self = this;
    setTimeout(function() {
      self._friendList.hidden = false;
    }, 0);
  },

  onTagTextInput: function(event) {
    var acceptButton = document.documentElement.getButton("accept");
    acceptButton.disabled = (this._tagText.value.length == 0);
    this._filterFriends(this._tagText.value);
  },

  onFriendListCommand: function(event) {
    var item = event.target;
    if (!item.friend)
      return;
    this._createPeopleTag(item.friend);
    window.close();
  }
};
