pref("extensions.facebook.notifications.toggle", true);
pref("extensions.facebook.notifications.you.req", true);
pref("extensions.facebook.notifications.you.msg", true);
pref("extensions.facebook.notifications.you.share", true);
pref("extensions.facebook.notifications.you.event.inv", true);
pref("extensions.facebook.notifications.you.group.inv", true);
pref("extensions.facebook.notifications.you.poke", true);
pref("extensions.facebook.notifications.you.friend", true);
pref("extensions.facebook.notifications.you.wall", true);
pref("extensions.facebook.notifications.friend.wall", false);
pref("extensions.facebook.notifications.friend.status", true);
pref("extensions.facebook.notifications.friend.note", true);
pref("extensions.facebook.notifications.friend.profile", true);
pref("extensions.facebook.notifications.friend.album", true);
pref("extensions.facebook.notifications.growl", false);
pref("extensions.facebook.notifications.growlpath", "/usr/local/bin/growlnotify");
pref("extensions.facebook.session_key", "" );
pref("extensions.facebook.session_secret", "" );
pref("extensions.facebook.uid", "" );
