pref("extensions.facebook.notifs.toggle", true);
pref("extensions.facebook.notifs.you.req", true);
pref("extensions.facebook.notifs.you.msg", true);
pref("extensions.facebook.notifs.you.share", true);
pref("extensions.facebook.notifs.you.poke", true);
pref("extensions.facebook.notifs.you.friend", true);
pref("extensions.facebook.notifs.you.wall", true);
pref("extensions.facebook.notifs.friend.wall", false);
pref("extensions.facebook.notifs.friend.status", true);
pref("extensions.facebook.notifs.friend.note", true);
pref("extensions.facebook.notifs.growl", false);
pref("extensions.facebook.notifs.growlpath", "/usr/local/bin/growlnotify");
pref("extensions.facebook.session_key", "" );
pref("extensions.facebook.session_secret", "" );
pref("extensions.facebook.uid", "" );