#include "nsISupports.idl"
#include "nsIRDFDataSource.idl"

[scriptable, uuid(46449e1d-69f3-4474-90a1-2aabaddf8447)]
interface fbIFacebookUser : nsISupports
{
    attribute AString id;
    attribute AString name;
    attribute AString pic;
    attribute AString status;
    attribute long    stime;
    attribute long    notes;
    attribute long    wall;
};

[scriptable, uuid(19baf81b-d1bd-4a99-9010-dd6f478bfd22)]
interface fbIFacebookService : nsISupports
{
    readonly attribute AString apiKey;
    readonly attribute AString secret;

    // login.xul is responsible for performing the login sequence.  Once that
    // is finished, it should call sessionStart, which initiates the polling
    // process.  If the session ever ends, the polling will stop until
    // sessionStart is called again.  Aside from the facebook.auth methods,
    // all other Facebook API calls should be done inside this service.
    void sessionStart(in AString sessionKey, in AString sessionSecret, in AString uid);
    void sessionEnd();

    // All other interaction comes by windows listing themselves as observers
    // and notifications that get triggered by the polling process.
    // Notifications that we fire:
    //   Topic                              Subject                      Data
    //   facebook-session-start             your fbIFacebookUser         your id
    //       (the session has started)                                   
    //   facebook-session-end               null                         null
    //
    //   facebook-new-req                   requester's fbIFacebookUser  requester's id
    //       (you have a new friend request)
    //   facebook-reqs-updated              null                         new req count
    //       (the count of reqs has been updated)
    //   facebook-new-msgs                  null                         new msg count
    //       (you have received new messages)
    //   facebook-msgs-updated              null                         new msg count
    //       (the count of msgs has been updated)
    //   facebook-new-poke                  null                         new poke count
    //       (you have received a new poke)
    //   facebook-pokes-updated             null                         new poke count
    //       (the count of pokes has been updated)
    //   facebook-wall-updated              null                         new wall count
    //       (the count of your wall posts has been updated)
    //
    //   facebook-new-friend                friend's fbIFacebookUser     friend's id
    //       (you have a new friend)
    //   facebook-friend-updated            updater's fbIFacebookUser    field updated
    //       (something updated about a friend - status msg, wall count, or notes count)
    //   facebook-friends-updated           null                         null
    //       (the collection of friends has been modified in some way)
    //
    // Windows can also query the most recent status of these things via the
    // readonly attributes below:
    readonly attribute boolean         loggedIn;
    readonly attribute fbIFacebookUser loggedInUser;
    readonly attribute long            numMsgs;
    readonly attribute long            numPokes;
    readonly attribute long            numReqs;
    void getFriends(out PRUint32 count, [retval,array,size_is(count)] out fbIFacebookUser users);
};
