#include "nsISupports.idl"

[scriptable, uuid(19baf81b-d1bd-4a99-9010-dd6f478bfd22)]
interface fbISimpleFacebookService : nsISupports
{
    attribute AString apiKey;
    attribute AString secret;

    attribute AString authToken;

    attribute AString sessionKey;
    attribute AString sessionSecret;
    attribute AString uid;

    attribute boolean loginPending;
};
